package com.ysdc.comet.data

import com.ysdc.comet.model.Team
import com.ysdc.comet.model.User
import io.reactivex.Completable
import io.reactivex.Single

interface DataManager{

    /**
     * Verify that the token is correct compare to the team we have in the app
     */
    fun isClubTokenValid(token : String) : Single<Boolean>

    /**
     * Add a new user and set the ID generated by the system, unless we find one with the same phone number and team ID.
     * In this case we simply return the user found.
     */
    fun addUser(user: User) : Single<User>

    /**
     * Update the user. Raise an error if no user found with its ID.
     */
    fun updateUser(user: User): Completable

    /**
     * Register the team on backend
     */
    fun registerTeam(team: Team): Completable
}